using IXM.SQL;

namespace IXM.SQL
{
    public class EventSQL : IEventSQL
    {

        public string GetEventsListing(string? pEvtId, string? pFieldName)
        {

            var lSql = " SELECT TPRJEVT.*, TPROJECT.DESCRIPTION PRJ_DESCRIPTION FROM TPRJEVT " +
                " LEFT OUTER JOIN TPROJECT ON TPRJEVT.PRJID = TPROJECT.PRJID WHERE TPRJEVT.PRJID IS NOT NULL ";

            if ((!string.IsNullOrEmpty(pEvtId)) && (pFieldName == "PEVTID"))
            {
                lSql = lSql + " AND TPRJEVT.PEVTID = " + pEvtId;
            }
            else if ((!string.IsNullOrEmpty(pEvtId)) && (!string.IsNullOrEmpty(pFieldName)) && (pFieldName != "PEVTID"))
            {
                lSql = lSql + " AND LOWER(TPRJEVT." + pFieldName + ") like '%" + pEvtId.ToLower() + "%'";
            }
            else if ((!string.IsNullOrEmpty(pEvtId)) && (pEvtId == "UP"))
            {
                lSql = lSql + " AND TPRJEVT.PSTDAT  >= CURRENT_TIMESTAMP";
            }
            ;

            return lSql;

        }


        public string GetEventDetailScan(string? pEventId, string? pSearchValue, string? pSearchField)
        {
            string[] fields = { "PEVTID", "PEVTDID", "SOURCEID" };

            var lSql = " SELECT TPRJEVTD.*,TPRJEVTD.STATUSID ORIG_STATUSID,MLOCALITY.DESCRIPTION LOCALITY_D, MEMPLOYEE.FULLNAME,MUNION.DESCRIPTION UNION_DESCRIPTION,MINTPOSITION.DESCRIPTION POSITION_DESCRIPTION, TPRJEVT.DESCRIPTION PRJ_DESCRIPTION, " +
            " MPROJECT.VENUE, MPROJECT.PSTDAT,MPROJECT.PENDATE,MEMPTYPE.DESCRIPTION EMPTYP_DESCRIPTION, MCOUNTRY.DESCRIPTION COUNTRY_DESCRIPTION, MEMPLOYEE.VE,MEMPLOYEE.CELLNUMBER,MSTATUS_TEXT.DESCRIPTION STATUS_DESCRIPTION, MSTATUS.DAM, " +
            " iif(MEMPLOYEE.MEMBERID IS NULL, 0, 1) ISMEMBER,MEMPLOYEE.MEMBERID,MEMPLOYEE.IDNUMBER,MEMPLOYEE.EMPID, MOBJECT_DOC.LT HASIMG, MMDOC.LT HASMIMG,MOBJECT_DOC.OBJECTID, MOBJECT_DOC.DOCUMENTNAME PDOCUMENTNAME, MOBJECT_DOC.DOCTYPE, " +
            " MCOMPANY.CNAME COMPANY_DNU, BCOMPANY.CNAME BCOMPANY_DNU, MMEMBER.EMPNUMBER, MEMPLOYEE.MNAME, MEMPLOYEE.MSURNAME, MCODE.CODE_FPATH FROM TPRJEVT " +
            " INNER JOIN TPRJEVTD ON TPRJEVT.PEVTID = TPRJEVTD.PEVTID  LEFT OUTER JOIN MPROJECT ON TPRJEVT.PRJID = MPROJECT.PRJID " +
            " LEFT OUTER JOIN MEMPLOYEE ON TPRJEVTD.SOURCEID = MEMPLOYEE.EMPID LEFT OUTER JOIN MEMPLOYEE MEMPLOYEER ON TPRJEVTD.RPLEMPID = MEMPLOYEER.EMPID " +
            " LEFT OUTER JOIN MMEMBER ON MEMPLOYEE.MEMBERID = MMEMBER.MEMBERID LEFT OUTER JOIN MCOMPANY ON MCOMPANY.COMPANYID = MMEMBER.COMPANYID " +
            " LEFT OUTER JOIN MCOMPANY BCOMPANY ON BCOMPANY.COMPANYID = MMEMBER.BCOMPANYID LEFT OUTER JOIN MLOCALITY ON MLOCALITY.LOCALITYID = MEMPLOYEE.LOCALITYID " +
            " LEFT OUTER JOIN MUNION ON MEMPLOYEE.UNIONID = MUNION.UNIONID LEFT OUTER JOIN MEMPTYPE ON MEMPLOYEE.EMPTYPID = MEMPTYPE.EMPTYPID " +
            " LEFT OUTER JOIN MSTATUS_TEXT ON TPRJEVTD.STATUSID = MSTATUS_TEXT.STATUSID LEFT OUTER JOIN MSTATUS ON TPRJEVTD.STATUSID = MSTATUS.STATUSID AND MSTATUS.STATUS_TYPE = 'TPRJEVTD' " +
            " LEFT OUTER JOIN MCOUNTRY ON MCOUNTRY.COUNTRYID = MEMPLOYEE.COUNTRYID LEFT OUTER JOIN MOBJECT_DOC ON MOBJECT_DOC.SOURCEID = MEMPLOYEE.EMPID AND MOBJECT_DOC.SOURCEOBJ = 'MEMPLOYEE' AND MOBJECT_DOC.DOCTYPE = 'EMPHOTO' " +
            " AND MOBJECT_DOC.SOURCEFLD = 'EMPID' AND MOBJECT_DOC.LT = 1 " +
            " LEFT OUTER JOIN MOBJECT_DOC MMDOC ON MMDOC.SOURCEID = MMEMBER.MEMBERID AND MMDOC.SOURCEOBJ = 'MMEMBER' AND MMDOC.DOCTYPE = 'MEMPHOTO' AND MMDOC.LT = 1 " +
            " LEFT OUTER JOIN MCODE ON MCODE.CODE_VALUE = MOBJECT_DOC.DOCTYPE " +
            " LEFT OUTER JOIN MINTPOSITION ON MEMPLOYEE.IPOSITIONID = MINTPOSITION.IPOSITIONID AND TPRJEVTD.SOURCEOBJ = 'MEMPLOYEE' WHERE TPRJEVT.PRJID IS NOT NULL AND TPRJEVT.PEVTID = " + pEventId;

            if (!string.IsNullOrEmpty(pSearchValue) && (Array.Find(fields, a => a == pSearchField) != null))
            {
                lSql = lSql + " AND TPRJEVTD." + pSearchField + " = " + pSearchValue;
            }
            else if (!string.IsNullOrEmpty(pSearchValue))
            {
                lSql = lSql + " AND LOWER(TPRJEVTD." + pSearchField + ") LIKE '%" + pSearchValue.ToLower() + "%'";
            }

            return lSql;
        }

        public string GetEventDetailListing(string? pSearchValue, string? pSearchField)
        {
            string[] fields = { "PEVTID", "PEVTDID", "SOURCEID" };

            var lSql = " SELECT TPRJEVTD.*,TPRJEVTD.STATUSID ORIG_STATUSID,MLOCALITY.DESCRIPTION LOCALITY_D, MEMPLOYEE.FULLNAME,MUNION.DESCRIPTION UNION_DESCRIPTION,MINTPOSITION.DESCRIPTION POSITION_DESCRIPTION, TPRJEVT.DESCRIPTION PRJ_DESCRIPTION, " +
                " MPROJECT.VENUE, MPROJECT.PSTDAT,MPROJECT.PENDATE,MEMPTYPE.DESCRIPTION EMPTYP_DESCRIPTION, MCOUNTRY.DESCRIPTION COUNTRY_DESCRIPTION, MEMPLOYEE.VE,MEMPLOYEE.CELLNUMBER,MSTATUS_TEXT.DESCRIPTION STATUS_DESCRIPTION, MSTATUS.DAM, " +
                " iif(MEMPLOYEE.MEMBERID IS NULL, 0, 1) ISMEMBER,MEMPLOYEE.MEMBERID,MEMPLOYEE.IDNUMBER,MEMPLOYEE.EMPID, MOBJECT_DOC.LT HASIMG, MMDOC.LT HASMIMG,MOBJECT_DOC.OBJECTID, MOBJECT_DOC.DOCUMENTNAME PDOCUMENTNAME, MOBJECT_DOC.DOCTYPE, " +
                " MCOMPANY.CNAME COMPANY_DNU, BCOMPANY.CNAME BCOMPANY_DNU, MMEMBER.EMPNUMBER, MEMPLOYEE.MNAME, MEMPLOYEE.MSURNAME, MCODE.CODE_FPATH FROM TPRJEVT " +
                " INNER JOIN TPRJEVTD ON TPRJEVT.PEVTID = TPRJEVTD.PEVTID  LEFT OUTER JOIN MPROJECT ON TPRJEVT.PRJID = MPROJECT.PRJID " +
                " LEFT OUTER JOIN MEMPLOYEE ON TPRJEVTD.SOURCEID = MEMPLOYEE.EMPID LEFT OUTER JOIN MEMPLOYEE MEMPLOYEER ON TPRJEVTD.RPLEMPID = MEMPLOYEER.EMPID " +
                " LEFT OUTER JOIN MMEMBER ON MEMPLOYEE.MEMBERID = MMEMBER.MEMBERID LEFT OUTER JOIN MCOMPANY ON MCOMPANY.COMPANYID = MMEMBER.COMPANYID " +
                " LEFT OUTER JOIN MCOMPANY BCOMPANY ON BCOMPANY.COMPANYID = MMEMBER.BCOMPANYID LEFT OUTER JOIN MLOCALITY ON MLOCALITY.LOCALITYID = MEMPLOYEE.LOCALITYID " +
                " LEFT OUTER JOIN MUNION ON MEMPLOYEE.UNIONID = MUNION.UNIONID LEFT OUTER JOIN MEMPTYPE ON MEMPLOYEE.EMPTYPID = MEMPTYPE.EMPTYPID " +
                " LEFT OUTER JOIN MSTATUS_TEXT ON TPRJEVTD.STATUSID = MSTATUS_TEXT.STATUSID LEFT OUTER JOIN MSTATUS ON TPRJEVTD.STATUSID = MSTATUS.STATUSID AND MSTATUS.STATUS_TYPE = 'TPRJEVTD' " +
                " LEFT OUTER JOIN MCOUNTRY ON MCOUNTRY.COUNTRYID = MEMPLOYEE.COUNTRYID LEFT OUTER JOIN MOBJECT_DOC ON MOBJECT_DOC.SOURCEID = MEMPLOYEE.EMPID AND MOBJECT_DOC.SOURCEOBJ = 'MEMPLOYEE' AND MOBJECT_DOC.DOCTYPE = 'EMPHOTO' " +
                " AND MOBJECT_DOC.SOURCEFLD = 'EMPID' AND MOBJECT_DOC.LT = 1 " +
                " LEFT OUTER JOIN MOBJECT_DOC MMDOC ON MMDOC.SOURCEID = MMEMBER.MEMBERID AND MMDOC.SOURCEOBJ = 'MMEMBER' AND MMDOC.DOCTYPE = 'MEMPHOTO' AND MMDOC.LT = 1 " +
                " LEFT OUTER JOIN MCODE ON MCODE.CODE_VALUE = MOBJECT_DOC.DOCTYPE " +
                " LEFT OUTER JOIN MINTPOSITION ON MEMPLOYEE.IPOSITIONID = MINTPOSITION.IPOSITIONID AND TPRJEVTD.SOURCEOBJ = 'MEMPLOYEE' WHERE TPRJEVT.PRJID IS NOT NULL ";

            if (!string.IsNullOrEmpty(pSearchValue) && (Array.Find(fields, a => a == pSearchField) != null))
            {
                lSql = lSql + " AND TPRJEVTD." + pSearchField + " = " + pSearchValue;
            }
            else if (!string.IsNullOrEmpty(pSearchValue))
            {
                lSql = lSql + " AND LOWER(TPRJEVTD." + pSearchField + ") LIKE '%" + pSearchValue.ToLower() + "%'";
            }

            return lSql;

        }

        public string GetEventStatsComponent(string? pEvtId)
        {
            var lSql = " SELECT " + pEvtId + " PEVTID, 'ComponentStats' REPORT, DelegateRegionStats.*  FROM (SELECT -1 ECOMPID, 'Registered Delegates' Component, Count(Distinct tprjevtd.sourceid ) Delegates " +
                " FROM TPRJEVTD WHERE PEVTID = " + pEvtId + " AND STATUSID NOT IN(select mstatus.statusid from  MSTATUS, mstatus_text " +
                " where MSTATUS.STATUSID = MSTATUS_TEXT.STATUSID AND MSTATUS.status_type LIKE 'TPRJEVTD' and mstatus.dam= -2) " +
                " union all " +
                " SELECT -2, 'Voting Delegates' StatusDescription, Count(Distinct tprjevtd.sourceid ) DelegateCount FROM TPRJEVTD " +
                " LEFT OUTER JOIN MEMPLOYEE ON TPRJEVTD.SOURCEID = MEMPLOYEE.EMPID " +
                " LEFT OUTER JOIN MEMPTYPE ON MEMPLOYEE.EMPTYPID = MEMPTYPE.EMPTYPID " +
                " WHERE PEVTID = " + pEvtId + " AND MEMPTYPE.EMPTYPID IN (3,14) " +
                " union all " +
                " SELECT MEVENT_COMPONENT.ECOMPID, MEVENT_COMPONENT.description StatusDescription, Count(Distinct tprjevtd.sourceid ) DelegateCount " +
                " FROM TPRJEVTD INNER JOIN TPRJEVTDD ON TPRJEVTDD.PEVTDID = TPRJEVTD.PEVTDID " +
                " INNER JOIN mevent_component ON MEVENT_COMPONENT.ECOMPID = TPRJEVTDD.ECOMPID " +
                " WHERE TPRJEVTD.PEVTID = " + pEvtId + " GROUP BY MEVENT_COMPONENT.ECOMPID, MEVENT_COMPONENT.description) DelegateRegionStats ";

            return lSql;
        }

        public string GetEventDetailComponent(string? pEvtId)
        {
            var lSql = " SELECT DelegateRegionStats.*  FROM (SELECT -1 ECOMPID, 'Registered Delegates' Component, Count(Distinct tprjevtd.sourceid ) Delegates " +
                " FROM TPRJEVTD WHERE PEVTID = " + pEvtId + " AND STATUSID NOT IN(select mstatus.statusid from  MSTATUS, mstatus_text " +
                " where MSTATUS.STATUSID = MSTATUS_TEXT.STATUSID AND MSTATUS.status_type LIKE 'TPRJEVTD' and mstatus.dam= -2) " +
                " union all " +
                " SELECT -2, 'Voting Delegates' StatusDescription, Count(Distinct tprjevtd.sourceid ) DelegateCount FROM TPRJEVTD " +
                " LEFT OUTER JOIN MEMPLOYEE ON TPRJEVTD.SOURCEID = MEMPLOYEE.EMPID " +
                " LEFT OUTER JOIN MEMPTYPE ON MEMPLOYEE.EMPTYPID = MEMPTYPE.EMPTYPID " +
                " WHERE PEVTID = " + pEvtId + " AND MEMPTYPE.EMPTYPID IN (3,14) " +
                " union all " +
                " SELECT MEVENT_COMPONENT.ECOMPID, MEVENT_COMPONENT.description StatusDescription, Count(Distinct tprjevtd.sourceid ) DelegateCount " +
                " FROM TPRJEVTD INNER JOIN TPRJEVTDD ON TPRJEVTDD.PEVTDID = TPRJEVTD.PEVTDID " +
                " INNER JOIN mevent_component ON MEVENT_COMPONENT.ECOMPID = TPRJEVTDD.ECOMPID " +
                " WHERE TPRJEVTD.PEVTID = " + pEvtId + " GROUP BY MEVENT_COMPONENT.ECOMPID, MEVENT_COMPONENT.description) DelegateRegionStats ";

            return lSql;
        }
        public string GetEventComponents(string? pEvtId)
        {
            var lSql = "SELECT CEVT_COMPONENT.ECOMPID,CEVT_COMPONENT.PEVTID, TPRJEVT.DESCRIPTION EVENT_DESCRIPTION,  MEVENT_COMPONENT.DESCRIPTION, MMSG.SMESSAGE, CEVT_COMPONENT.MSGID,CEVT_COMPONENT.MSGACTIVE,CEVT_COMPONENT.ISACTIVE FROM CEVT_COMPONENT " +
                " INNER JOIN MEVENT_COMPONENT ON CEVT_COMPONENT.ECOMPID = MEVENT_COMPONENT.ECOMPID " +
                " INNER JOIN TPRJEVT ON TPRJEVT.PEVTID = CEVT_COMPONENT.PEVTID " +
                " LEFT JOIN MMSG ON MMSG.MSGID = CEVT_COMPONENT.MSGID " +
                " WHERE CEVT_COMPONENT.PEVTID = " + pEvtId;

            return lSql;
        }

        public string GetEventStatsEmpType(string? pEvtId)
        {
            var lSql = " SELECT " + pEvtId + " PEVTID,'EmpTypeStats' REPORT, DelegateStats.* FROM (SELECT MEMPTYPE.EMPTYPID ECOMPID, MEMPTYPE.DESCRIPTION Component, Count(tprjevtd.sourceid ) Delegates, " +
                " Sum(IIF(MEMPTYPE.emptypid= 3,1,0)) VotingDelegateCount FROM TPRJEVTD " +
                " LEFT OUTER JOIN MEMPLOYEE ON TPRJEVTD.SOURCEID = MEMPLOYEE.EMPID LEFT OUTER JOIN MMEMBER ON MEMPLOYEE.MEMBERID = MMEMBER.MEMBERID " +
                " LEFT OUTER JOIN MCOMPANY ON MCOMPANY.COMPANYID = MMEMBER.BCOMPANYID LEFT OUTER JOIN MEMPTYPE ON MEMPLOYEE.EMPTYPID = MEMPTYPE.EMPTYPID " +
                " LEFT OUTER JOIN MLOCALITY ON MEMPLOYEE.LOCALITYID = MLOCALITY.LOCALITYID WHERE PEVTID = " + pEvtId + " AND MEMPTYPE.EGROUP > 0 " +
                " GROUP BY MEMPTYPE.EMPTYPID, MEMPTYPE.DESCRIPTION ) DelegateStats ";
            return lSql;
        }

        public string GetEventProgramme(string pEvtId)
        {

            var lSql = " SELECT TPRJEVTS.*, MPROJECT.DESCRIPTION PRJ_DESCRIPTION FROM TPRJEVTS " +
            " INNER JOIN TPRJEVT ON TPRJEVT.PEVTID = TPRJEVTS.PEVTID " +
            " LEFT OUTER JOIN MPROJECT ON TPRJEVT.PRJID = MPROJECT.PRJID WHERE TPRJEVT.PRJID IS NOT NULL ";

            if ((!string.IsNullOrEmpty(pEvtId)))
            {
                lSql = lSql + " AND TPRJEVT.PEVTID = " + pEvtId;
            }
            ;

            return lSql;


        }


    }
}
