// <auto-generated />
using System;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using IXM.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IXM.API.Migrations
{
    [DbContext(typeof(IXMDBContext))]
    partial class IXMDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);

            modelBuilder.Entity("IXM.API.Models.APP_HARDCODES", b =>
                {
                    b.Property<string>("HARDC_TYPE")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("HARDCODEID")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("HVALUE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("HARDC_TYPE");

                    b.ToTable("APP_HARDCODES");
                });

            modelBuilder.Entity("IXM.API.Models.IXMChartData", b =>
                {
                    b.Property<string>("ChartKey")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Color")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LabelGroupDescription")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LabelGroupId")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LabelGroupName")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LabelValue")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("ChartKey");

                    b.ToTable("IXMChartData");
                });

            modelBuilder.Entity("IXM.API.Models.MBANKNAME", b =>
                {
                    b.Property<int>("BANKNAMEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_BY")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SHORT_CODE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("UNIVERSALCODE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("BANKNAMEID");

                    b.ToTable("MBANKNAME");
                });

            modelBuilder.Entity("IXM.API.Models.MCITY", b =>
                {
                    b.Property<string>("CITYID")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("CITYPE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ISACTIVE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("NOTES")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PCITYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POSTCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PROVINCEID")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("CITYID");

                    b.ToTable("MCITY");
                });

            modelBuilder.Entity("IXM.API.Models.MCOMPANY", b =>
                {
                    b.Property<int>("COMPANYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BCITYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BPROVINCEID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BUILDINGNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("BUILDINGNO")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CELL_NUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CNAME")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("COMDTYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("COMPANYINFO")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("COMPANYNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("COMPTYPID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CONTACT_PERSON")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("EXT_COCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("E_MAIL")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FAX_NUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MAREA")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("MEMCOUNT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OLD_CCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POSTALCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("RCOMPANYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("REG_NUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("SECTORID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SECTORNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STREETNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("STREETNO")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TEL_NUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TO_INVOICE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("WEBADDRESS")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("COMPANYID");

                    b.ToTable("MCOMPANY");
                });

            modelBuilder.Entity("IXM.API.Models.MCOMPANY_CCUR", b =>
                {
                    b.Property<int>("COMPANYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BCITYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BPROVINCEID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BUILDINGNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("BUILDINGNO")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CELL_NUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CNAME")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("COMDTYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("COMPANYINFO")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("COMPANYNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("COMPTYPID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CONTACT_PERSON")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("EXT_COCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("E_MAIL")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FAX_NUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MAREA")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("MEMCOUNT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OLD_CCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POSTALCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PROCESSOR_CELLNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PROCESSOR_EMAIL")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PROCESSOR_NAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("RCOMPANYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("REG_NUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("SECTORID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SECTORNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STREETNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("STREETNO")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TEL_NUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TO_INVOICE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("WEBADDRESS")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("COMPANYID");

                    b.ToTable("MCOMPANY_CCUR");
                });

            modelBuilder.Entity("IXM.API.Models.MCOMPTYPE", b =>
                {
                    b.Property<int>("COMPTYPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ADLVL")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ALVL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DCODE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("LEVEL_N")
                        .HasColumnType("INTEGER");

                    b.HasKey("COMPTYPID");

                    b.ToTable("MCOMPTYPE");
                });

            modelBuilder.Entity("IXM.API.Models.MLOCALITY", b =>
                {
                    b.Property<int>("LOCALITYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BUILDINGNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BUILDINGNO")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CITYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FAXNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GEOLATI")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GEOLONG")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ISLOCAL")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LOCTYPE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LSC")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PLOCALITYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POSTALCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PROVINCEID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STREETNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STREETNO")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TELNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("LOCALITYID");

                    b.ToTable("MLOCALITY");
                });

            modelBuilder.Entity("IXM.API.Models.MMCDD", b =>
                {
                    b.Property<int>("CDDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CDID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("INSBY")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime?>("INSDAT")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("LT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MEMBERID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PNAME")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PSURNAME")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("WI")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("CDDID");

                    b.ToTable("MMCDD");
                });

            modelBuilder.Entity("IXM.API.Models.MMEMBER", b =>
                {
                    b.Property<int>("MEMBERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ANNUAL_SALARY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("BCOMPANYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CELLNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CITYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("COMPANYID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DBCONTRIBUTION")
                        .HasColumnType("DOUBLE PRECISION");

                    b.Property<string>("DOB")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("EMAIL")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("EMPLOYDATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("EMPNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("ETHNICID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EXTNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GENDER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("HTEL_NO")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("IDNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("IDTYPEID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INITIALS")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("JOINDATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("KNOWNAS")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("LOCALITYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MARSTAT")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MEMBERNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MSURNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MemCardReceived")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("POSITIONID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SALARY")
                        .HasColumnType("DOUBLE PRECISION");

                    b.Property<int?>("SECTORID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TITLE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("UNIONID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YOS")
                        .HasColumnType("INTEGER");

                    b.HasKey("MEMBERID");

                    b.ToTable("MMEMBER");
                });

            modelBuilder.Entity("IXM.API.Models.MMEMBER_ADD", b =>
                {
                    b.Property<int>("ADDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDTYPE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BUILDINGNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("BUILDINGNO")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("CITYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("MEMBERID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POBOXNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POBOXNO")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POBOXPREFIX")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POCITYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POPOSTALCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("POSTALCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STREETNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STREETNO")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STREETNOPF")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("ADDID");

                    b.ToTable("MMEMBER_ADD");
                });

            modelBuilder.Entity("IXM.API.Models.MMEMBER_BANK", b =>
                {
                    b.Property<int>("MEMBANKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACCOUNTNUMBER")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("BANKNAMEID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BRANCHCODE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DDOP")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("DEDUCTIONSTATUSID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("MEMBERID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("NOTES")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("MEMBANKID");

                    b.ToTable("MMEMBER_BANK");
                });

            modelBuilder.Entity("IXM.API.Models.MMEMBER_NONPAYMENT", b =>
                {
                    b.Property<int>("MEMBERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MSURNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MemCardReceived")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("MEMBERID");

                    b.ToTable("MMEMBER_NONPAYMENT");
                });

            modelBuilder.Entity("IXM.API.Models.MMEMBER_NOT", b =>
                {
                    b.Property<int>("NOTEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CELLNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("MEMBERID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NOTES")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("NOTETYPE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PNOTEID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SOURCEID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SOURCEOBJ")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STATUSID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("NOTEID");

                    b.ToTable("MMEMBER_NOT");
                });

            modelBuilder.Entity("IXM.API.Models.MOBJECT_DOC", b =>
                {
                    b.Property<int>("OBJECTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DOCTYPE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DOCUMENTNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime?>("EFFDATE")
                        .HasColumnType("TIMESTAMP");

                    b.Property<double?>("FILESIZE")
                        .HasColumnType("DOUBLE PRECISION");

                    b.Property<string>("FILEXTENSION")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime?>("INSERT_DATE")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("LDOCUMENTNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LFOLDERNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("LMACHINENAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("LT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SFOLDERNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SOURCEFLD")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("SOURCEID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SOURCEOBJ")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("OBJECTID");

                    b.ToTable("MOBJECT_DOC");
                });

            modelBuilder.Entity("IXM.API.Models.MOBJECT_DOCFILE", b =>
                {
                    b.Property<int>("OBJECTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DOCUMENTNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("IMAGEURI")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("LT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SFOLDERNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("OBJECTID");

                    b.ToTable("MOBJECT_DOCFILE");
                });

            modelBuilder.Entity("IXM.API.Models.MPERIOD", b =>
                {
                    b.Property<int>("PRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EDATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FDESCRIPTION")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FMONTH")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FYEAR")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MDESCRIPTION")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MIMONTH")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MYEAR")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("QT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SDATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("PRID");

                    b.ToTable("MPERIOD");
                });

            modelBuilder.Entity("IXM.API.Models.MPROVINCE", b =>
                {
                    b.Property<string>("PROVINCEID")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("COUNTRYID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SVG_MAP")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("PROVINCEID");

                    b.ToTable("MPROVINCE");
                });

            modelBuilder.Entity("IXM.API.Models.MSECTOR", b =>
                {
                    b.Property<int>("SECTORID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CORDINATORID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("COUNCILID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("HSECTORID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SHORT_DESCRIPTION")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("SECTORID");

                    b.ToTable("MSECTOR");
                });

            modelBuilder.Entity("IXM.API.Models.MSTATUS", b =>
                {
                    b.Property<int>("MSTATUSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CA")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("DAM")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IDAM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ISACTIVE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("KSH")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SCM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("SCQ")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SGRP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SHF")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SHORT_CODE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("STATUSID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("STATUS_SEQ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("STATUS_TYPE")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("TABLEID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WFID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("MSTATUSID");

                    b.ToTable("MSTATUS");
                });

            modelBuilder.Entity("IXM.API.Models.MSTATUS_TEXT", b =>
                {
                    b.Property<int>("STATUSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ISACTIVE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("STATUSID");

                    b.ToTable("MSTATUS_TEXT");
                });

            modelBuilder.Entity("IXM.API.Models.MUNION", b =>
                {
                    b.Property<int>("UNIONID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CINDSID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSBY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSDT")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SHORTDESC")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("UNIONID");

                    b.ToTable("MUNION");
                });

            modelBuilder.Entity("IXM.API.Models.MUSER", b =>
                {
                    b.Property<int>("USERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CELLNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("EMAILADDRESS")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("LOCALITYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SURNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TELNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("UGID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("UPASSWORD")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("USERID");

                    b.ToTable("MUSER");
                });

            modelBuilder.Entity("IXM.API.Models.MUSER_AUTH", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DeviceCode")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("LockoutEnd")
                        .HasColumnType("VARCHAR(48)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("BOOLEAN");

                    b.Property<int?>("USERID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IXM.API.Models.MUSER_GROUP", b =>
                {
                    b.Property<int>("UGID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BRANCHVIEWTYPE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DTVT")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("GRTP")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERTED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("INSERT_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ISACTIVE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_BY")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MODIFIED_DATE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("UGCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("UGID");

                    b.ToTable("MUSER_GROUP");
                });

            modelBuilder.Entity("IXM.API.Models.ORGANISER_COMPANY", b =>
                {
                    b.Property<int>("COMPANYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CELL_NUMBER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNAME")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("COMPANYNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("COMPTYPID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CONTACT_PERSON")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("EXT_COCODE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("E_MAIL")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("IAMOUNT")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("MMEMCOUNT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("PAYMENTID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PAYMENTNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("PERIODID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PMEMCOUNT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PROCESSOR_CELLNUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PROCESSOR_EMAIL")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PROCESSOR_NAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("REG_NUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("STIC")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("TEL_NUMBER")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("WEBADDRESS")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("COMPANYID");

                    b.ToTable("ORGANISER_COMPANY");
                });

            modelBuilder.Entity("IXM.API.Models.REP_PROCESSORWORK", b =>
                {
                    b.Property<int>("ROW_NUMBER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNAME")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ISLOADED")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PAYMENT")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PAYMENTID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PERIODID")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SURNAME")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("USERID")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("USER_COMPANY")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("ROW_NUMBER");

                    b.ToTable("REP_PROCESSORWORK");
                });

            modelBuilder.Entity("IXM.API.Models.SEQUENCE", b =>
                {
                    b.Property<int>("SEQVALUE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SEQVALUE");

                    b.ToTable("SEQUENCE");
                });

            modelBuilder.Entity("IXM.API.Models.STATSBRANCH", b =>
                {
                    b.Property<int>("PERIODID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("COMPANYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("COMPANYNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<double?>("IAMOUNT")
                        .HasColumnType("DOUBLE PRECISION");

                    b.Property<int?>("MMEMCOUNT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("PAYMENTNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<double?>("PMEMCOUNT")
                        .HasColumnType("DOUBLE PRECISION");

                    b.Property<int?>("USERID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PERIODID");

                    b.ToTable("STATSBRANCH");
                });

            modelBuilder.Entity("IXM.API.Models.STATSREGION", b =>
                {
                    b.Property<int>("MEMBERS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LOCALITYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MAX_FYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("MIN_FYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("REGIONAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("MEMBERS");

                    b.ToTable("STATSREGION");
                });

            modelBuilder.Entity("IXM.API.Models.TDSURVEY_C", b =>
                {
                    b.Property<int>("SURVEYDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DATATYPE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FIELDNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("FIELDVALUE")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime?>("INSERTDATE")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("SURVEYID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SURVEYDID");

                    b.ToTable("TDSURVEY_C");
                });

            modelBuilder.Entity("IXM.API.Models.TMEMPAYMENT", b =>
                {
                    b.Property<int>("PAYMENTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("COMPANYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("COMPANYNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("MEMBERID")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PAMOUNT")
                        .HasColumnType("DOUBLE PRECISION");

                    b.Property<string>("PAYMENTNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("PERIODID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("PAYMENTID");

                    b.ToTable("TMEMPAYMENT");
                });

            modelBuilder.Entity("IXM.API.Models.TPAYMENT", b =>
                {
                    b.Property<int>("PAYMENTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNAME")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("COMPANYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("COMPANYNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int?>("MEMCOUNT")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PAMOUNT")
                        .HasColumnType("DOUBLE PRECISION");

                    b.Property<string>("PAYMENTNUM")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<int>("PERIODID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PYEARMONTH")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("PAYMENTID");

                    b.ToTable("TPAYMENT");
                });

            modelBuilder.Entity("IXM.API.Models.TSURVEYMEMBERDATA", b =>
                {
                    b.Property<int>("MEMBERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BCOMPANYID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SRVY_QU01")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU02")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU03")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU04")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU05")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU06")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU07")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU08")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU09")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("SRVY_QU10")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<DateTime>("SURVEYDATE")
                        .HasColumnType("TIMESTAMP");

                    b.Property<int>("SURVEYID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MEMBERID");

                    b.ToTable("TSURVEYMEMBERDATA");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.ToTable("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
